set_property CFGBVS VCCO [current_design] 
set_property CONFIG_VOLTAGE 3.3 [current_design] 
set_property BITSTREAM.GENERAL.COMPRESS true [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 

set_property -dict {PACKAGE_PIN R4 IOSTANDARD DIFF_SSTL15} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD DIFF_SSTL15} [get_ports sys_clk_n] 

set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports sys_rstn] 

set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {sw[0]}] 
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {sw[1]}] 
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {sw[2]}] 
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {sw[3]}] 
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {sw[4]}] 
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {sw[5]}] 
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {sw[6]}] 
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {sw[7]}] 
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {sw[8]}] 
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {sw[9]}] 
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {sw[10]}] 
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {sw[11]}] 
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports {sw[12]}] 
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {sw[13]}] 

set_property -dict {PACKAGE_PIN Y18  IOSTANDARD TMDS_33} [get_ports hdmi_clk_p]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD TMDS_33} [get_ports hdmi_clk_n]
set_property -dict {PACKAGE_PIN V18  IOSTANDARD TMDS_33} [get_ports hdmi_data0_p]
set_property -dict {PACKAGE_PIN V19  IOSTANDARD TMDS_33} [get_ports hdmi_data0_n]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD TMDS_33} [get_ports hdmi_data1_p]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD TMDS_33} [get_ports hdmi_data1_n]
set_property -dict {PACKAGE_PIN V17  IOSTANDARD TMDS_33} [get_ports hdmi_data2_p]
set_property -dict {PACKAGE_PIN W17  IOSTANDARD TMDS_33} [get_ports hdmi_data2_n]